project:
  type: website
  output-dir: docs

website:
  favicon: "figs/jk.ico"
  page-navigation: true
  back-to-top-navigation: true
  title: "Jhon K. Flores Rojas"
  repo-url: https://github.com/tjhon/jhon
  repo-actions:
    - source
    - edit
    - issue
  twitter-card:
    creator: "@jhon"
    site: "@jhon"
  navbar:
    title: Jhon K.
    right:
      - icon: folder
        href: blog/index.qmd
        text: Blog
      - icon: palette
        text: Data Viz
        href: data_viz/index.qmd
      - icon: terminal
        text: Projects
        href: projects/index.qmd
      - icon: table
        text: Tidy Data
        href: data_tidy/index.qmd
      - icon: github
        href: https://github.com/tjhon
    left:
      - href: index.qmd
        text: Home
        icon: house
      - icon: person-lines-fill
        href: about/index.qmd
        text: About
  page-footer:
    border: false
    left: "Jhon Flores Rojas"
    center:
      - icon: github
      - icon: twitter
      - icon: linkedin
      - icon: instagram
format:
  html:
    code-tools:
      source: true
      toggle: true
      caption: "Opciones de codigo"
    link-external-newwindow: true
    theme:
      light:
        - litera
        - _assets/colors
        - _assets/light-var.scss
        - _assets/theme_jk.scss
      dark:
        - litera
        - _assets/colors
        - _assets/dark-var.scss
        - _assets/theme_jk.scss
    toc: true
    page-layout: full
    code-overflow: wrap
    highlight-style:
      light: _assets/light-code.theme
      dark: _assets/dark-code.theme

editor: visual
execute:
  freeze: auto
