project:
  type: website
  output-dir: docs

website:
  title: JhonFR
  favicon: "_assets/icons/fr-logo.ico"

  navbar:
    title: Jhon FR
    right:
      # - icon: folder
      #   text: Blog
      - icon: palette
        text: DataViz
        href: qmds/dataviz/dataviz.qmd
      - icon: terminal
        text: Projects
        href: qmds/projects/projects.qmd
      # - icon: bar-chart-steps
      #   text: Data Analysis
      - icon: github
        href: https://github.com/tjhon
    left:
      - icon: house
        text: Home
        href: index.qmd

  page-footer:
    border: false
    left: "Jhon Flores Rojas"
    right: "Made with [quarto](https://quarto.org/)"

format:
  html:
    link-external-newwindow: true

    theme:
      light:
        - litera
        - _assets/scss/theme.scss
        - _assets/scss/light-var.scss
      dark:
        - litera
        - _assets/scss/theme.scss
        - _assets/scss/dark-var.scss

    highlight-style:
      light: _assets/highlight/light.theme
      dark: _assets/highlight/dark.theme

    # toc: true
    # code-tools:
    #   source: true
    #   toggle: true
    #   caption: "Código"
    code-overflow: wrap
    # code-block-border-left: true

    # page-layout: 80vw

lang: es
editor: source
execute:
  freeze: true
  # freeze: auto
